### PR TITLE
Add strict mode authentication

### PR DESCRIPTION
**Pull request by taharah**

### CODE REVIEW

**Comment by StephanErb** [comment]
What kind of authentication system is this? It does not seem to be part of Mesos, so I assume it is an extension of DC/OS?

**Comment by taharah** [comment]
@StephanErb it's an extension of DC/OS and not part of the open source version of Mesos.

**Comment by lloesche** [comment]
@taharah thank you for the PR! Can we make it more explicit to the user when he's using DC/OS IAM authentication as opposed to just Mesos authentication?

`mesos_exporter` is a 100% community maintained Prometheus Exporter for Apache Mesos. Adding support for Mesos running in DC/OS strict mode makes a lot of sense but should be explicitly labeled as such by changing help strings to e.g.
`Username to use for HTTP or DC/OS strict mode authentication`
And renaming flags to for instance `-dcosLoginURL` instead of `-loginURL`, `-dcosStrictMode` instead of `-strictMode`, etc.

Also since strict mode is an EE only feature most of the community members here won't have access to it hence will be unable to test this PR. Which is likely the reason it's been laying around for so long until I just stumbled upon it. I will find qualified Go Devs within Mesosphere to test and review your contribution.

@StephanErb I'll have someone test the changes on a DC/OS EE cluster and do the code review on a technical/functional level. Could I kindly ask you to provide guidance regarding naming of flags and help texts? Like I mentioned, I'd like to make it very explicit to the user when he's using standalone Mesos vs. when he's using Mesos within strict security mode DC/OS.

**Comment by taharah** [comment]
@lloesche I'll try to make your suggested changes this week, which I agree will help minimize confusion for those that are not running the EE of DC/OS. Moreover, I think it would be great to get some unit testing created in order to properly test this. I've been running it internally on our clusters for a few months now so I can independently verify it works; however, some automated testing is definitely always preferred. I'm not very familiar with Golang unit testing, so that would take me a bit to implement for this specific PR.

**Pull request merged**
