### PR TITLE
Additional Metrics

### PR DESCRIPTION
**Pull request by elubow**
This pull request includes laying out all the metrics for:
* masters
* agents
* /monitor/statistics

### CODE REVIEW

**Comment by philipnrmn** [comment]
@StephanErb how so?

**Comment by elubow** [comment]
I only had 1 existing deployment to test it on and it didn't break it. I'm also following this up with another PR which has much better error handling.

**Comment by StephanErb** [comment]
For example, the metric `mem_rss_bytes` was renamed to "mesos_agent_mem_rss_bytes`. I totally agree that the new name is better, but it is very hard to deploy into a production environment with dozens of dashboards and alert configurations. 

Normally changes like this are done by providing a metric relabelling config, so that both metrics can co-exist at the same time. For example, there is currently a similar issue in the Prometheus node exporter https://github.com/prometheus/node_exporter/issues/830

**Comment by StephanErb** [comment]
I did not intend to sound so harsh. Besides of the breaking naming change this contribution looks great! I am sure we can figure it out :)

**Comment by elubow** [comment]
Part of the issue here is that some of the metrics aren't even being collected all the time.  For instance `threads` is a really generic name. So I'm not sure how a relabel would help there as it's so generic it might actually make things worse depending on the environment. I can certainly create a diff of metric names. But that also won't account for metrics that have migrated to submetrics with labels. At least I couldn't see a way to handle that scenario from prometheus/node_exporter#830.  Any solution we come up with would be half-baked at best.

Also, it's only harsh until constructive feedback transpires :) Point taken, but we definitely have some issues that I don't see a path to resolution for.

**Comment by philipnrmn** [comment]
Not at all harsh - this is very fair criticism, I was trigger-happy on the merge. I'll make sure we get a relabelling config in today.

**Pull request merged**
