### PR TITLE
Fix #12: Scrape Mesos task labels

### LINKED ISSUE #12: Use Mesos task labels as prometheus labels
Mesos is support task labels. (https://mesosphere.com/blog/2015/03/27/mesos-0-22-0-released/) . Task labels are available via  `/monitor/statistics`:

``` json
...
{
  "executor_id": "default",
  "framework_id": "20150312-120017-16777343-5050-39028-0000",
  "id": "3",
  "labels": [
    {
      "key": "environment",
      "value": "prod"
    },
    {
      "key": "bananas",
      "value": "apples"
    }
  ],
  "name": "Task 3",
  "slave_id": "20150312-115625-16777343-5050-38751-S0",
  "state": "TASK_FINISHED",
  ...
},
```

We should attach those task labels to our the scraped tasks metrics (e.g. `mem_rss_bytes`) as Prometheus labels.

Given that the cluster operators and the users submitting Mesos tasks with attached labels are different administrative domains, we should optionally consider to introduce whitelisting to prevent spamming the metric system with thousands of user-defined labels.

### PR DESCRIPTION
**Pull request by jonashaag**
This adds a new series, `mesos_slave_task_labels`, that has a value of constant `1` and includes user-specified labels. Example:

```
$ ./mesos_exporter ... -exportedTaskLabels="my.first.label,my.second.label"
```

will export a series like:

```
mesos_slave_task_labels{my_first_label="custom value1",my_second_label="custom value 2",
cluster="...",executor_id="...",framework_id="...",instance="...",job="mesos-slave",source="..."}
```

Note two limitations by Prometheus here:
- Labels to be included must be specified upfront
- Labels are normalised to `[a-zA-Z0-9_]+`
### Adding task labels to other series

While the `task_labels` series isn't of much use on its own, it may be used to add task labels to other time series. For example, if we want to annotate `mem_limit_bytes` with our custom labels, we can use a query like this:

```
mem_limit_bytes * on (source) group_left(my_first_label) mesos_slave_task_labels
```

(The idea for these kind of "joins" stems from here: http://www.robustperception.io/exposing-the-software-version-to-prometheus/)

### CODE REVIEW

**Comment by lloesche** [comment]
@jonashaag thank you for the PR! Can you please rebase this and #17 ?
I'll make sure to get it merged asap.

**Comment by jonashaag** [comment]
Rebased

**Comment by jonashaag** [comment]
@lloesche bump

**Comment by StephanErb** [comment]
I tried to test this and it doesn't work: We cannot assume that a label is available on all tasks. 

```
./mesos_exporter -slave="http://agent1.mesos.example.org" -addr=127.0.0.1:9091 -exportedTaskLabels=org.apache.aurora.tier
2016/11/04 11:44:26 Exposing slave metrics on 127.0.0.1:9091
panic: inconsistent label cardinality

goroutine 53 [running]:
panic(0x2cf4c0, 0xc4200757e0)
        prometheus/mesos_exporter/.build/go1.7.3/src/runtime/panic.go:500 +0x1a1
github.com/prometheus/client_golang/prometheus.(*MetricVec).With(0xc4201165c0, 0xc42032b350, 0x32feda, 0x1)
        prometheus/mesos_exporter/.build/gopath/src/github.com/prometheus/client_golang/prometheus/vec.go:146 +0x88
github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc420106088, 0xc42032b350, 0xc420102820, 0x1)
        prometheus/mesos_exporter/.build/gopath/src/github.com/prometheus/client_golang/prometheus/gauge.go:115 +0x3c
main.newSlaveStateCollector.func1(0xc4201a8ae0, 0x4828a0, 0xc420106088)
        prometheus/mesos_exporter/slave_state.go:87 +0x48d
main.(*slaveStateCollector).Collect(0xc420102880, 0xc420112780)
        prometheus/mesos_exporter/slave_state.go:116 +0x2fb
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc420102c10, 0xc420112780, 0x482ba0, 0xc420102880)
        prometheus/mesos_exporter/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x63
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        prometheus/mesos_exporter/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x326
```

**Comment by jonashaag** [comment]
@serb Missing labels are now set to `""`, which are ignored by Prometheus by design (IIUC).

**Pull request merged**
